/*
 * Copyright (c) 2018, Xdevelnet (xdevelnet at xdevelnet dot org)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#if !defined strizeof
#define strizeof(a) (sizeof(a)-1)
#endif

const char p1[] = "<!--\n"
	"/* clock.html\n"
	" *\n"
	" * Copyright (c) 2017, Xdevelnet (xdevelnet at xdevelnet dot org)\n"
	" * All rights reserved.\n"
	" *\n"
	" * Redistribution and use in source and binary forms, with or without\n"
	" * modification, are permitted provided that the following conditions are met:\n"
	" * Redistributions of source code must retain the above copyright notice, this\n"
	" * list of conditions and the following disclaimer.\n"
	" * Redistributions in binary form must reproduce the above copyright notice,\n"
	" * this list of conditions and the following disclaimer in the documentation\n"
	" * and/or other materials provided with the distribution.\n"
	" * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\n"
	" * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
	" * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
	" * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE\n"
	" * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
	" * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\n"
	" * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
	" * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\n"
	" * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
	" * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
	" */\n"
	"-->\n"
	"\n"
	"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n"
	"\t\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"
	"<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n"
	"\n"
	"<head>\n"
	"\t<title>ffclock - fastcgi fancy clock</title>\n"
	"\t<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" />\n"
	"\t<script type=\"text/css\">\n"
	"\t</script>\n"
	"\t<style>\n"
	"\thtml {\n"
	"\t\theight: 100%;\n"
	"\t}\n"
	"\tbody {\n"
	"\t\tbackground-color: #F9F9F9;\n"
	"\t\tfont-family: Arial, sans-serif;\n"
	"\t\tmargin: 0px;\n"
	"\t\tpadding: 0px;\n"
	"\t\tcolor: #272727;\n"
	"\t\theight: 100%;\n"
	"\t}\n"
	"\t.time_and_text {\n"
	"\t\tfont-size: 500%;\n"
	"\t\tpadding-top: 1%;\n"
	"\t}\n"
	"\t.circle {\n"
	"\t\tbackground: #d6d6d6;\n"
	"\t\twidth: 400pt;\n"
	"\t\theight: 400pt;\n"
	"\t\tborder-radius: 50%;\n"
	"\t\tdisplay: inline-block;\n"
	"\t\tposition: relative;\n"
	"\t\ttext-align: center;\n"
	"\t\tmargin-top: 1%;\n"
	"\t}\n"
	"\t.arrow {\n"
	"\t\tposition: absolute;\n"
	"\t\tdisplay: block;\n"
	"\t\twidth: 100%;\n"
	"\t\theight: 2%;\n"
	"\t\tleft: 0%;\n"
	"\t\tright: 0%;\n"
	"\t\ttop: 49%;\n"
	"\t\tborder: 0px;\n"
	"\t}\n"
	"\t#rotate {\n"
	"\t\t-sand-transform: rotate(";
const char p2[] = "deg);\n"
	"\t\t-webkit-transform: rotate(";
const char p3[] = "deg);\n"
	"\t\t-moz-transform: rotate(";
const char p4[] = "deg);\n"
	"\t\ttransform: rotate(";
const char p5[] = "deg);\n"
	"\t}\n"
	"\t#rotatem {\n"
	"\t\t-sand-transform: rotate(";
const char p6[] = "deg);\n"
	"\t\t-webkit-transform: rotate(";
const char p7[] = "deg);\n"
	"\t\t-moz-transform: rotate(";
const char p8[] = "deg);\n"
	"\t\ttransform: rotate(";
const char p9[] = "deg);\n"
	"\t}\n"
	"\t#rotate1 {\n"
	"\t\t-sand-transform: rotate(30deg);\n"
	"\t\t-webkit-transform: rotate(30deg);\n"
	"\t\t-moz-transform: rotate(30deg);\n"
	"\t\ttransform: rotate(30deg);\n"
	"\t}\n"
	"\t#rotate2 {\n"
	"\t\t-sand-transform: rotate(60deg);\n"
	"\t\t-webkit-transform: rotate(60deg);\n"
	"\t\t-moz-transform: rotate(60deg);\n"
	"\t\ttransform: rotate(60deg);\n"
	"\t}\n"
	"\t#rotate3 {\n"
	"\t\t-sand-transform: rotate(90deg);\n"
	"\t\t-webkit-transform: rotate(90deg);\n"
	"\t\t-moz-transform: rotate(90deg);\n"
	"\t\ttransform: rotate(90deg);\n"
	"\t}\n"
	"\t#rotate4 {\n"
	"\t\t-sand-transform: rotate(120deg);\n"
	"\t\t-webkit-transform: rotate(120deg);\n"
	"\t\t-moz-transform: rotate(120deg);\n"
	"\t\ttransform: rotate(120deg);\n"
	"\t}\n"
	"\t#rotate5 {\n"
	"\t\t-sand-transform: rotate(150deg);\n"
	"\t\t-webkit-transform: rotate(150deg);\n"
	"\t\t-moz-transform: rotate(150deg);\n"
	"\t\ttransform: rotate(150deg);\n"
	"\t}\n"
	"\t#rotate6 {\n"
	"\t\t-sand-transform: rotate(180deg);\n"
	"\t\t-webkit-transform: rotate(180deg);\n"
	"\t\t-moz-transform: rotate(180deg);\n"
	"\t\ttransform: rotate(180deg);\n"
	"\t}\n"
	"\t#rotate7 {\n"
	"\t\t-sand-transform: rotate(210deg);\n"
	"\t\t-webkit-transform: rotate(210deg);\n"
	"\t\t-moz-transform: rotate(210deg);\n"
	"\t\ttransform: rotate(210deg);\n"
	"\t}\n"
	"\t#rotate8 {\n"
	"\t\t-sand-transform: rotate(240deg);\n"
	"\t\t-webkit-transform: rotate(240deg);\n"
	"\t\t-moz-transform: rotate(240deg);\n"
	"\t\ttransform: rotate(240deg);\n"
	"\t}\n"
	"\t#rotate9 {\n"
	"\t\t-sand-transform: rotate(270deg);\n"
	"\t\t-webkit-transform: rotate(270deg);\n"
	"\t\t-moz-transform: rotate(270deg);\n"
	"\t\ttransform: rotate(270deg);\n"
	"\t}\n"
	"\t#rotate10 {\n"
	"\t\t-sand-transform: rotate(300deg);\n"
	"\t\t-webkit-transform: rotate(300deg);\n"
	"\t\t-moz-transform: rotate(300deg);\n"
	"\t\ttransform: rotate(300deg);\n"
	"\t}\n"
	"\t#rotate11 {\n"
	"\t\t-sand-transform: rotate(330deg);\n"
	"\t\t-webkit-transform: rotate(330deg);\n"
	"\t\t-moz-transform: rotate(330deg);\n"
	"\t\ttransform: rotate(330deg);\n"
	"\t}\n"
	"\t#rotate12 {\n"
	"\t\t-sand-transform: rotate(0deg);\n"
	"\t\t-webkit-transform: rotate(0deg);\n"
	"\t\t-moz-transform: rotate(0deg);\n"
	"\t\ttransform: rotate(0deg);\n"
	"\t}\n"
	"\t.black {\n"
	"\t\tposition: relative;\n"
	"\t\twidth: 49%;\n"
	"\t\theight: 100%;\n"
	"\t\tleft: 50%;\n"
	"\t\tbackground-color: #505050;\n"
	"\t}\n"
	"\t.blacke {\n"
	"\t\tposition: relative;\n"
	"\t\twidth: 20%;\n"
	"\t\theight: 100%;\n"
	"\t\tleft: 50%;\n"
	"\t\tbackground-color: black;\n"
	"\t}\n"
	"\t.blackp {\n"
	"\t\tposition: relative;\n"
	"\t\twidth: 7%;\n"
	"\t\theight: 100%;\n"
	"\t\tleft: 93%;\n"
	"\t\tbackground-color: black;\n"
	"\t}\n"
	"\t</style>\n"
	"</head>\n"
	"<body><table border=\"0\" width=\"100%\" height=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
	"<tr valign=\"bottom\" height=\"60%\"><td align=\"center\">\n"
	"\t<div class=\"circle\">\n"
	"\t\t<div class=\"arrow\" id=\"rotate\">\n"
	"\t\t\t<div class=\"black\"></div>\n"
	"\t\t</div>\n"
	"\t\t<div class=\"arrow\" id=\"rotatem\">\n"
	"\t\t\t<div class=\"blacke\"></div>\n"
	"\t\t</div>\n"
	"\t\t<div class=\"arrow\" id=\"rotate1\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate2\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate3\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate4\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate5\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate6\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate7\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate8\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate9\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate10\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate11\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t\t\n"
	"\t\t<div class=\"arrow\" id=\"rotate12\">\n"
	"\t\t\t<div class=\"blackp\"></div>\n"
	"\t\t</div>\n"
	"\t</div></td></tr>\n"
	"\t<tr valign=\"top\"><td align=\"center\" class=\"time_and_text\">";
const char p10[] = "</td></tr>\n"
	"\t</table>\n"
	"</body>\n"
	"</html>";
